app:
  name: 'personal-recall'

paths:
  # Base directory for the app (dont put a slash at the end & put the base directory only, a subfolder will be created with the app_name)
  base_dir: "C:\\Users\\sutk\\.analytics"
  backup_base_dir: "C:\\Users\\sutk\\OneDrive - Deloitte (O365D)\\.analytics"

session:
  lock_stale_minutes: 30 # minutes to wait before a session becomes stale
  minutes: 15 # length of each chunk
  idle_threshold: 600 # (60 * 10) seconds of idle to allow video processing

capture:
  interval: 5 # seconds between screenshots
  webp_quality: 100 # 0-100 lossy quality
  hash_size: 8 # dHash dimensions -> 8x8 -> 64-bit
  hamming_threshold: 12 # larger -> less sensitive
  persistence_frames: 2 # require N consecutive frames crossing threshold
  area_small_pxl: 128 # resolution to compute changed-area fraction
  area_frac_threshold: 0.015 # fraction of pixels changed to consider (1.5%)

video:
  ffmpeg: 'ffmpeg' # rely on PATH. If needed, set absolute path.
  fps: 3 # session video FPS
  summary_video_fps: 20 # summary video FPS

client:
  port: 5000 # Port for the client to connect
  timeline_limit: 5000 # Timeline API Max Image Limit

local_retention:
  days: 7 # How many days to keep local data before deletion
  backup_freq_hrs: 6 # How often to backup data in hours
